apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: lb-sample
  annotations:
    description: LB Sample
  labels:
    app: lb-sample
    os.template.kubevirt.io/fedora: 'true'
  namespace: vms-loadbalancer
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: example
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: q35
        memory:
          guest: 2Gi
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/fedora
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: fedora
              chpasswd: { expire: False }
              bootcmd:
                - "sudo yum install httpd -y"
                - "sudo systemctl enable httpd.service --now"
                - "sudo echo \"Hey, I am VM $(hostname)!\" > /var/www/html/index.html"
          name: cloudinitdisk
