# https://github.com/openshift/cluster-logging-operator/blob/master/docs/features/logforwarding/outputs/otlp-forwarding.adoc

apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-collector
  namespace: openshift-logging
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: collect-application-logs
subjects:
  - kind: ServiceAccount
    name: log-collector
    namespace: openshift-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collect-application-logs
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: collect-infrastructure-logs
subjects:
  - kind: ServiceAccount
    name: log-collector
    namespace: openshift-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collect-infrastructure-logs
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: collect-audit-logs
subjects:
  - kind: ServiceAccount
    name: log-collector
    namespace: openshift-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collect-audit-logs
---
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
#  annotations:
#    observability.openshift.io/tech-preview-otlp-output: "enabled"
  name: logging
  namespace: openshift-logging
spec:
  managementState: Managed
  outputs:
    - loki:
        url: 'http://3.129.40.240:3100'
      name: logging-loki
      type: loki
    - name: otlp
      type: otlp
      tls:
        insecureSkipVerify: true
#      otlp:
#        authentication:
#          token:
#            from: serviceAccount
#        tuning:
#          compression: gzip
#        url: 'http://otel-receiver-collector.observability.svc.cluster.local:4318/v1/logs'
  pipelines:
    - inputRefs:
        - application
        - infrastructure
        - audit
      name: logs-to-loki
      outputRefs:
        - logging-loki
#    - inputRefs:
#      - application
#      - infrastructure
#      - audit
#      name: otlp-logs
#      outputRefs:
#      - otlp        
  serviceAccount:
    name: log-collector

