apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan201-bond0
spec:
#  nodeSelector:
#    node-role.kubernetes.io/worker: ''
#    kubernetes.io/hostname: node-name
  desiredState:
    interfaces:
      - description: vlan201 using bond0
        ipv4:
          enabled: false
        name: bond0.201
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 201
      - bridge:
          allow-extra-patch-ports: true
          options:
            stp:
              enabled: false
          port:
            - name: bond0.201
        description: Bridge on VLAN201 using bond0
        ipv4:
          enabled: false
        name: br-201
        state: up
        type: ovs-bridge
    ovn:
      bridge-mappings:
        - bridge: br-201
          localnet: ovs-bridge-vlan201
          state: present