apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan200-bond0
spec:
#  nodeSelector:
#    node-role.kubernetes.io/worker: ''
#    kubernetes.io/hostname: node-name
  desiredState:
    interfaces:
      - description: vlan200 using bond0
        ipv4:
          enabled: false
        name: bond0.200
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 4
      - bridge:
          allow-extra-patch-ports: true
          options:
            stp:
              enabled: false
          port:
            - name: bond0.200
        description: Bridge on VLAN200 using bond0
        ipv4:
          enabled: false
        name: br-200
        state: up
        type: ovs-bridge
    ovn:
      bridge-mappings:
        - bridge: br-200
          localnet: ovs-bridge-vlan200
          state: present