apiVersion: velero.io/v1
kind: Restore
metadata:
  name: rocket-chat-2
  namespace: openshift-adp
spec:
  backupName: rocketchat-1
  includedNamespaces:
    - rocketchat
  includedResources:
    - replicationcontroller
    - deploymentconfig
    - templateinstances.template.openshift.io
  restorePVs: true
