apiVersion: velero.io/v1
kind: Restore
metadata:
  name: rocket-chat-1
  namespace: openshift-adp
spec:
  backupName: rocketchat-1
  excludedResources:
    - replicationcontroller
    - deploymentconfig
    - templateinstances.template.openshift.io
  includedNamespaces:
    - rocketchat
  restorePVs: true